
# Example Nav2 configuration parameters
amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    map_topic: "map"

map_server:
  ros__parameters:
    yaml_filename: /home/ayman/tiago_ws/src/tiago_navigation_config/maps/my_map.yaml
    use_sim_time: True

planner_server:
  ros__parameters:
    use_sim_time: True


controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.1
    max_x_velocity: 0.26
    max_y_velocity: 0.0
    max_theta_velocity: 1.0
    goal_checker_plugins: ["goal_checker"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.26
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: -0.26
      max_speed_xy: 0.26
      min_speed_theta: -1.0
      max_speed_theta: 1.0
      min_speed: -0.26
      max_speed: 0.26
      sim_time: 1.7
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: 0.5
      decel_lim_y: 0.0
      decel_lim_theta: 1.0
      rotate_to_heading_angular_vel: 0.0
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      critics: ["ObstacleFootprint", "GoalAlign", "PathAlign", "GoalDist", "PathDist"]
      PathAlign:
        scale: 24.0
      GoalAlign:
        scale: 32.0
      PathDist:
        scale: 32.0
      GoalDist:
        scale: 24.0
      ObstacleFootprint:
        scale: 0.02
        radius: 0.46
        safety_distance: 0.02
      oscillation_reset_dist: 0.05
      prune_plan: True

bt_navigator:
  ros__parameters:
    use_sim_time: True

lifecycle_manager:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names:
      - "map_server"
      - "amcl"
      - "planner_server"
      - "controller_server"
      - "bt_navigator"

global_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 1.0
    publish_frequency: 1.0
    resolution: 0.05
    size_x: 50.0
    size_y: 50.0
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"

local_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: "odom"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    size_x: 10.0
    size_y: 10.0
    plugins: ["voxel_layer", "inflation_layer"]

    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"

